version: "3.8"

services:
  mysql-server:
    image: mysql:8
    container_name: mysql_server
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=curso10
    ports:
      - "3307:3306"
    networks:
      - net-curso10
    volumes:
      - data-mysql-vol:/var/lib/mysql

  redis-server:
    image: redis:6.0.5-alpine
    container_name: redis_server
    command: redis-server --requirepass todovale
    ports:
      - "6379:6379"
    restart: always
    networks:
      - net-curso10

  sonarqube-server:
    image: sonarqube:8-community
    container_name: sonarqube_server
    ports:
      - "9000:9000"
      - "9092:9092"
    restart: always
    networks:
      - net-curso10

networks:
  net-curso10:

volumes:
  data-mysql-vol:
